spring.application.name=GamblingIsEvil
spring.docker.compose.enabled=true
spring.datasource.url=jdbc:h2:mem:GamblingIsEvil
spring.jpa.hibernate.ddl-auto=create-drop

# JWT Configuration
jwt.secret=2XZCFnmx0gac6Obn7LVsXtxpT36eCKJBGEbXg3luFuN2
jwt.expiration=360000

# game data provider (openLigaDb, ...)
gamedata.provider = openLigaDb
# odds provider (oddsApi, ...)
odds.provider = oddsApi

# OddsApi
api.key=6e022ec60bd8bfee56511b20e62ff66a