spring.application.name=KumpelLiga
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=2XZCFnmx0gac6Obn7LVsXtxpT36eCKJBGEbXg3luFuN2
jwt.expiration=360000

# game data provider (openLigaDb, ...)
gamedata.provider = openLigaDb
# odds provider (oddsApi, ...)
odds.provider = oddsApi

# OddsApi
api.key=6e022ec60bd8bfee56511b20e62ff66a