spring.application.name=KumpelLiga
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# game data provider (openLigaDb, ...)
gamedata.provider=${GAMEDATA_PROVIDER}
# odds provider (oddsApi, ...)
odds.provider=${ODDS_PROVIDER}

# OddsApi
api.key=${ODDS_API_KEY}

# syncdata
sync.cron.games =${SYNC_CRON_GAMES}
sync.cron.odds =${SYNC_CRON_ODDS}
sync.cron.payout =${SYNC_CRON_PAYOUT}